
spring:
  datasource:
    url: jdbc:h2:mem:banco
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update #create-drop